spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 12345678
        url: jdbc:mysql://localhost:3306/ecommerce
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
        show-sql: true

security:
    oauth2:
      client:
        registration:
          github:
            clientId: 
            clientSecret:      
  
                  
divinexcode:
    app:
        jwtExpirationMs: 86400000
        jwtSecret: CodebyGauravSecretKey

server:
    port: 8888
                  